{
  "hash": "94cc735714b69a63a0ebe83aeb52a107",
  "result": {
    "engine": "knitr",
    "markdown": "# Week 9: Multiple Linear Regression {#sec-week09-01}\n\n## Why This Matters\n\nThe advertising model from Module 4 so far uses only `tv` to predict `sales`, but the company obviously spends on more than just TV, it also runs radio and online advertising. A model that explains sales using TV spend alone is ignoring information sitting right there in the data, and worse, if radio or online spend happen to be related to TV spend, the simple model's slope could be partly capturing their effects too, without saying so. **Multiple linear regression** extends the least-squares idea from @sec-week08-01 to more than one predictor at once, letting us ask a sharper question: what is the effect of TV spend specifically, *after accounting for* radio and online spend?\n\n## The Multiple Regression Model\n\nWith $k$ predictors, the model becomes\n$$\n\\hat{y} = b_0 + b_1x_1 + b_2x_2 + \\cdots + b_kx_k\n$$\nJust as in simple regression, the $b$'s are chosen to minimize the sum of squared residuals, $\\sum(y_i-\\hat{y}_i)^2$, now across all $k$ predictors simultaneously. The formulas for computing them by hand get complicated fast (they involve matrix algebra), so from here on we'll rely on software, but the underlying least-squares idea, minimize the total squared prediction error, hasn't changed at all.\n\nThe key difference in interpretation: each slope $b_j$ now represents the predicted change in $y$ for a one-unit increase in $x_j$, **holding all other predictors in the model fixed**. This \"holding fixed\" phrase is doing real work, it's what lets us separate TV's effect from radio's and online's, rather than lumping them together the way a simple regression using only `tv` would.\n\n::: {.example title=\"Example 9.1: Adding radio spend to the model\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nads <- read_csv(\"data/advertising.csv\")\n\nmodel_tv_radio <- lm(sales ~ tv + radio, data = ads)\nsummary(model_tv_radio)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ tv + radio, data = ads)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.1738 -1.3360  0.1579  1.3179  6.2233 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 7.332284   0.377091   19.44   <2e-16 ***\ntv          0.052258   0.001690   30.93   <2e-16 ***\nradio       0.137012   0.009854   13.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.03 on 197 degrees of freedom\nMultiple R-squared:  0.8556,\tAdjusted R-squared:  0.8541 \nF-statistic: 583.4 on 2 and 197 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nThe fitted model is\n$$\n\\widehat{\\text{sales}} = 7.33 + 0.0523\\,(\\text{tv}) + 0.1370\\,(\\text{radio})\n$$\n:::\n\n## Interpreting the Coefficients\n\n::: {.example title=\"Example 9.2: What each slope means\"}\nContinuing Example 9.1:\n\n- **$b_{\\text{tv}} = 0.0523$**: holding radio spend fixed, each additional \\$1,000 spent on TV advertising is associated with about \\$52.30 more in sales, on average.\n- **$b_{\\text{radio}} = 0.1370$**: holding TV spend fixed, each additional \\$1,000 spent on radio advertising is associated with about \\$137.00 more in sales, on average, a noticeably larger return per dollar than TV in this model.\n- **$b_0 = 7.33$**: predicted sales when both TV and radio spend are \\$0.\n\nCompare $b_{\\text{tv}}=0.0523$ here to the simple regression's slope of $0.0527$ from @sec-week08-01, they're close but not identical. Adding radio to the model changed the TV coefficient slightly, because part of what the simple model's slope was picking up has now been separated out and credited to radio instead.\n:::\n\n::: {.callout-important collapse=\"false\" title=\"\\\"Holding other predictors constant\\\" is a statement about the model, not the real world\"}\nThis model can describe *what the data show* when TV and radio spend vary somewhat independently of each other, but it cannot literally hold radio spend fixed while TV spend changes in reality. If TV and radio spend are themselves strongly related (for instance, campaigns that increase one tend to increase the other), separating their individual effects becomes far less reliable, an issue called **multicollinearity**, covered in @sec-week10-01. For this dataset, TV and radio spend are only weakly correlated ($r \\approx 0.02$), so their effects can be estimated fairly cleanly here.\n:::\n\n## Building Out the Full Model\n\nNothing stops us from adding the third channel as well.\n\n::: {.example title=\"Example 9.3: The full three-predictor model\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_full <- lm(sales ~ tv + radio + online, data = ads)\nsummary(model_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ tv + radio + online, data = ads)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.4101 -1.2197  0.0381  1.3658  6.1457 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 6.419406   0.392732  16.346  < 2e-16 ***\ntv          0.051235   0.001595  32.123  < 2e-16 ***\nradio       0.132689   0.009269  14.316  < 2e-16 ***\nonline      0.030092   0.005650   5.326 2.74e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.902 on 196 degrees of freedom\nMultiple R-squared:  0.8738,\tAdjusted R-squared:  0.8719 \nF-statistic: 452.4 on 3 and 196 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nThe fitted model is\n$$\n\\widehat{\\text{sales}} = 6.42 + 0.0512\\,(\\text{tv}) + 0.1327\\,(\\text{radio}) + 0.0301\\,(\\text{online})\n$$\nAll three slopes are positive and statistically significant ($p<0.0001$ for each), holding the other two predictors fixed: TV, radio, and online spend are each associated with higher sales, even after accounting for the other two channels.\n:::\n\n## R-Squared vs. Adjusted R-Squared\n\nRecall from @sec-week08-02 that $R^2$ measures the proportion of variability in $y$ explained by the model. A mechanical fact about $R^2$ in multiple regression: **adding any predictor to a model, even a useless one, can never decrease $R^2$**, and will almost always increase it at least slightly, simply because the least-squares fit has one more piece of information to work with. That makes raw $R^2$ a poor way to decide whether an added predictor is *actually* worth including.\n\n**Adjusted $R^2$** fixes this by penalizing the number of predictors in the model:\n$$\nR^2_{\\text{adj}} = 1 - (1-R^2)\\frac{n-1}{n-k-1}\n$$\nwhere $k$ is the number of predictors. Unlike $R^2$, adjusted $R^2$ can go *down* when a predictor is added that doesn't pull its weight, making it a fairer way to compare models with different numbers of predictors.\n\n::: {.example title=\"Example 9.4: Comparing the three models\"}\n| Model | Predictors | $R^2$ | Adjusted $R^2$ |\n|---|---|---|---|\n| Simple (@sec-week08-01) | tv | 0.714 | 0.712 |\n| Two-predictor (Example 9.1) | tv, radio | 0.856 | 0.854 |\n| Full (Example 9.3) | tv, radio, online | 0.874 | 0.872 |\n\nBoth $R^2$ and adjusted $R^2$ climb substantially when radio is added (0.714 to 0.856), and climb again, more modestly, when online is added (0.856 to 0.874). Because adjusted $R^2$ increases right alongside $R^2$ at each step, this is a sign that radio and online are both contributing genuine explanatory power, not just inflating $R^2$ by being present. Had a predictor added little real information, $R^2$ might have ticked up by a tiny amount while adjusted $R^2$ actually fell, a signal that the added complexity wasn't worth it.\n:::\n\n## The Overall F-Test\n\nAlongside each predictor's individual t-test, multiple regression output also reports an overall F-test:\n$$\nH_0: \\beta_1 = \\beta_2 = \\cdots = \\beta_k = 0 \\qquad H_a: \\text{at least one } \\beta_j \\neq 0\n$$\nThis tests whether the predictors, **taken together**, explain a significant amount of variability in $y$, the same logic as the ANOVA F-test from @sec-week07-01, now applied to a regression model instead of group means.\n\n::: {.example title=\"Example 9.5: The overall F-test for the full model\"}\nFrom Example 9.3's output, $F = 452.4$ on $(3, 196)$ degrees of freedom, $p<0.0001$. We reject $H_0$: at least one of TV, radio, and online spend has a real relationship with sales.\n:::\n\n::: {.callout-note collapse=\"false\" title=\"The F-test and the individual t-tests are no longer the same question\"}\n@sec-week08-02 showed that in *simple* regression, the F-test and the slope's t-test always agree, $F=t^2$, because there's only one predictor to test. With multiple predictors, that's no longer true. The overall F-test asks whether the predictors are jointly useful *as a group*; each t-test asks whether one specific predictor adds anything, *given that the others are already in the model*. It's entirely possible for the overall F-test to be significant while one particular predictor's t-test is not, that predictor simply isn't pulling its own weight once the others are accounted for.\n:::\n\n## Making a Prediction\n\n::: {.example title=\"Example 9.6: Predicting sales from all three channels\"}\nWhat sales would the full model predict for a market spending \\$150k on TV, \\$25k on radio, and \\$40k on online advertising?\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model_full, newdata = data.frame(tv = 150, radio = 25, online = 40))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n18.62552 \n```\n\n\n:::\n:::\n\n:::\n\n## Computing Multiple Regression in R and Excel\n\n::: {.example title=\"Example 9.7: The full model in R and Excel\"}\nIn R, additional predictors are simply added with `+` inside `lm()`, as shown throughout this section:\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(sales ~ tv + radio + online, data = ads)\n```\n:::\n\n\nIn Excel, the Data Analysis ToolPak's **Regression** tool accepts multiple predictor columns at once, as long as they sit in **contiguous columns**, select all three (`tv`, `radio`, `online`) as the \"Input X Range\" and `sales` as the \"Input Y Range.\" The output table reports each coefficient, its standard error, t-statistic, and p-value, along with $R^2$, adjusted $R^2$, and the overall F-test, in the same layout as R's `summary()` output above.\n:::\n\n## Recap\n\n| **Keyword** | **Definition** |\n|---|---|\n| **Multiple linear regression** | $\\hat{y}=b_0+b_1x_1+\\cdots+b_kx_k$; extends simple regression to more than one predictor. |\n| **Holding other predictors constant** | Each slope $b_j$ describes the predicted effect of $x_j$ on $y$ after accounting for the other predictors already in the model. |\n| **Adjusted $R^2$** | $R^2$ penalized for the number of predictors, $1-(1-R^2)\\frac{n-1}{n-k-1}$; can decrease when an added predictor isn't useful, unlike raw $R^2$. |\n| **Overall F-test** | Tests $H_0:\\beta_1=\\cdots=\\beta_k=0$; whether the predictors, jointly, explain significant variability in $y$. |\n| **Multicollinearity (preview)** | When predictors are strongly related to each other, individual coefficient estimates become unreliable; covered fully in @sec-week10-01. |\n\n## Check Your Understanding\n\n::: {.callout-note collapse=\"false\" title=\"Problems\"}\n1. A multiple regression predicting employee performance rating from `years_tenure` and `training_hours` gives $b_{\\text{tenure}} = 0.35$ and $b_{\\text{training}} = 0.08$. Interpret each coefficient in a full sentence, being explicit about what's being held constant.\n\n2. A model with 2 predictors has $R^2=0.61$; adding a third predictor raises $R^2$ to $0.615$ but lowers adjusted $R^2$ from $0.605$ to $0.598$. What does this pattern suggest about the third predictor, and which number, $R^2$ or adjusted $R^2$, should drive the decision to keep it?\n\n3. A regression of monthly revenue on `ad_spend` and `store_size` produces an overall F-test with $p<0.0001$, but the t-test for `store_size` alone has $p=0.41$. Explain how both results can be true at the same time, and what it implies about `store_size`'s role in this particular model.\n\n4. Explain, in your own words, why $R^2$ can never decrease when a predictor is added to a model, while adjusted $R^2$ can.\n\n5. Using the full advertising model from Example 9.3 ($\\widehat{\\text{sales}} = 6.42 + 0.0512\\,\\text{tv} + 0.1327\\,\\text{radio} + 0.0301\\,\\text{online}$), predict sales for a market spending \\$100k on TV, \\$10k on radio, and \\$0 on online advertising.\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Solutions\"}\n1. Holding training hours constant, each additional year of tenure is associated with a predicted 0.35-point increase in performance rating, on average. Holding years of tenure constant, each additional hour of training is associated with a predicted 0.08-point increase in performance rating, on average.\n\n2. This pattern suggests the third predictor adds little genuine explanatory power, it nudges $R^2$ up only slightly (as any added predictor mechanically tends to), but adjusted $R^2$, which penalizes for the added complexity, actually falls, indicating the small gain in fit isn't worth the added predictor. The decision should be driven by **adjusted $R^2$**, not raw $R^2$, precisely because raw $R^2$ can't fall even when a predictor isn't pulling its weight.\n\n3. The overall F-test asks whether `ad_spend` and `store_size`, **together**, explain significant variability in revenue, while the t-test for `store_size` asks whether it contributes significantly **given that `ad_spend` is already in the model**. It's entirely possible for `ad_spend` alone to be driving nearly all of the joint significance, while `store_size` adds little once `ad_spend` is already accounted for, which is exactly what a high-significance F-test paired with a non-significant `store_size` t-test implies here.\n\n4. Adding a predictor gives the least-squares fitting process one more piece of information to work with, so it can never do worse (in terms of matching the observed $y$ values) than it did without that predictor, and will almost always do at least marginally better, even from a predictor with no real relationship to $y$, just by chance alone. Adjusted $R^2$ explicitly subtracts a penalty that grows with the number of predictors, $k$, in the denominator $n-k-1$, so if a new predictor's improvement to $R^2$ is smaller than what that added penalty costs, adjusted $R^2$ falls even though raw $R^2$ rose.\n\n5. $\\widehat{\\text{sales}} = 6.42 + 0.0512(100) + 0.1327(10) + 0.0301(0) = 6.42 + 5.12 + 1.327 + 0 = 12.867$, predicted sales of about \\$12,867.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}